---
abstract: 'interface to OpenSSH authorized_keys data'
author:
  - 'Jeremy Mates <jmates@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-OpenSSH-Authkey
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  IO::Handle: 0
  Test::More: 0
  perl: 5
resources:
  homepage: https://github.com/thrig/Config-OpenSSH-Authkey
  license: http://dev.perl.org/licenses/
  repository: https://github.com/thrig/Config-OpenSSH-Authkey
version: 1.02
